import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { Sidebar, Navbar } from "@/components"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "BeTrusty",
  description: "Generated by Eric Saucedo",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex">
          <Sidebar />
          <div className="w-full">
            <Navbar />
            <main className="flex flex-col px-6 md:px-16 h-[calc(100vh-80px)] overflow-y-auto custom-scrollbar">
              {children}
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
